"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 06:09:15.566451
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if op.get_context().dialect.name == "mysql":
        # Persian text requires utf8mb4 regardless of how the database was created.
        op.execute("ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_group'), ['group'], unique=False)

    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_customers', sa.Integer(), nullable=True),
    sa.Column('max_tickets_per_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_mb', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('secondary_color', sa.String(length=9), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('ticket_prefix', sa.String(length=10), nullable=False),
    sa.Column('ticket_seq', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_companies_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_active'), ['is_active'], unique=False)

    op.create_table('faq_categories',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_faq_categories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_categories'))
    )
    with op.batch_alter_table('faq_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_categories_company_id'), ['company_id'], unique=False)

    op.create_table('holidays',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_holidays_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('company_id', 'date', name=op.f('uq_holidays_company_id_date'))
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_company_id'), ['company_id'], unique=False)

    op.create_table('knowledge_base_categories',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_knowledge_base_categories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_categories')),
    sa.UniqueConstraint('company_id', 'slug', name=op.f('uq_knowledge_base_categories_company_id_slug'))
    )
    with op.batch_alter_table('knowledge_base_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_base_categories_company_id'), ['company_id'], unique=False)

    op.create_table('roles',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_roles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_roles_company_id_name'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_company_id'), ['company_id'], unique=False)

    op.create_table('ticket_priorities',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_priorities_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_priorities')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_ticket_priorities_company_id_code'))
    )
    with op.batch_alter_table('ticket_priorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_priorities_company_id'), ['company_id'], unique=False)

    op.create_table('ticket_statuses',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('pauses_sla', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_statuses_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_statuses')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_ticket_statuses_company_id_code'))
    )
    with op.batch_alter_table('ticket_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_statuses_company_id'), ['company_id'], unique=False)

    op.create_table('ticket_tags',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_tags_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_tags')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_ticket_tags_company_id_name'))
    )
    with op.batch_alter_table('ticket_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_tags_company_id'), ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('mobile_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('mobile', name=op.f('uq_users_mobile'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_type'), ['user_type'], unique=False)

    op.create_table('audit_logs',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_company_created', ['company_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('departments',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_strategy', sa.String(length=20), nullable=False),
    sa.Column('last_assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_assigned_user_id'], ['users.id'], name=op.f('fk_departments_last_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_departments_manager_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('faqs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['faq_categories.id'], name=op.f('fk_faqs_category_id_faq_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_faqs_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.create_index('ix_faqs_company_order', ['company_id', 'category_id', 'sort_order'], unique=False)

    op.create_table('knowledge_base_articles',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_knowledge_base_articles_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_base_categories.id'], name=op.f('fk_knowledge_base_articles_category_id_knowledge_base_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_knowledge_base_articles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_articles')),
    sa.UniqueConstraint('company_id', 'slug', name=op.f('uq_knowledge_base_articles_company_id_slug'))
    )
    with op.batch_alter_table('knowledge_base_articles', schema=None) as batch_op:
        batch_op.create_index('ix_kb_articles_company_status', ['company_id', 'status', 'views'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_articles_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('notification_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('sms', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_settings')),
    sa.UniqueConstraint('user_id', 'event', name=op.f('uq_notification_settings_user_id_event'))
    )
    op.create_table('notifications',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_notifications_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at', 'created_at'], unique=False)

    op.create_table('password_resets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_resets_token_hash'))
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_sessions_user_active', ['user_id', 'revoked_at'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('verification_codes',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_codes'))
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index('ix_verification_codes_target', ['target', 'purpose', 'created_at'], unique=False)

    op.create_table('department_users',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_users_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_department_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id', 'user_id', name=op.f('pk_department_users'))
    )
    with op.batch_alter_table('department_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_users_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_base_feedback',
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_base_articles.id'], name=op.f('fk_knowledge_base_feedback_article_id_knowledge_base_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_base_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_feedback')),
    sa.UniqueConstraint('article_id', 'user_id', name=op.f('uq_knowledge_base_feedback_article_id_user_id'))
    )
    op.create_table('sla_rules',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('priority_id', sa.String(length=36), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('warning_percent', sa.Integer(), nullable=False),
    sa.Column('business_hours_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sla_rules_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_sla_rules_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_id'], ['ticket_priorities.id'], name=op.f('fk_sla_rules_priority_id_ticket_priorities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_rules'))
    )
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.create_index('ix_sla_rules_lookup', ['company_id', 'is_active', 'priority_id', 'department_id'], unique=False)

    op.create_table('ticket_categories',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('default_agent_id', sa.String(length=36), nullable=True),
    sa.Column('default_priority_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_categories_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_agent_id'], ['users.id'], name=op.f('fk_ticket_categories_default_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_priority_id'], ['ticket_priorities.id'], name=op.f('fk_ticket_categories_default_priority_id_ticket_priorities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_ticket_categories_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['ticket_categories.id'], name=op.f('fk_ticket_categories_parent_id_ticket_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_categories'))
    )
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_categories_company_parent', ['company_id', 'parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_categories_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('tickets',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('priority_id', sa.String(length=36), nullable=False),
    sa.Column('status_id', sa.String(length=36), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('last_response_at', sa.DateTime(), nullable=True),
    sa.Column('last_customer_reply_at', sa.DateTime(), nullable=True),
    sa.Column('last_agent_reply_at', sa.DateTime(), nullable=True),
    sa.Column('first_responded_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('sla_rule_id', sa.String(length=36), nullable=True),
    sa.Column('first_response_due_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=True),
    sa.Column('sla_status', sa.String(length=20), nullable=False),
    sa.Column('sla_paused_at', sa.DateTime(), nullable=True),
    sa.Column('sla_warning_notified', sa.Boolean(), nullable=False),
    sa.Column('sla_breach_notified', sa.Boolean(), nullable=False),
    sa.Column('first_response_breached', sa.Boolean(), nullable=False),
    sa.Column('resolution_breached', sa.Boolean(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], name=op.f('fk_tickets_assigned_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name=op.f('fk_tickets_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_tickets_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tickets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_tickets_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_tickets_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['priority_id'], ['ticket_priorities.id'], name=op.f('fk_tickets_priority_id_ticket_priorities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rules.id'], name=op.f('fk_tickets_sla_rule_id_sla_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['ticket_statuses.id'], name=op.f('fk_tickets_status_id_ticket_statuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('company_id', 'number', name=op.f('uq_tickets_company_id_number'))
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_code'), ['code'], unique=False)
        batch_op.create_index('ix_tickets_company_agent', ['company_id', 'assigned_agent_id', 'status_id'], unique=False)
        batch_op.create_index('ix_tickets_company_category', ['company_id', 'category_id'], unique=False)
        batch_op.create_index('ix_tickets_company_created', ['company_id', 'created_at'], unique=False)
        batch_op.create_index('ix_tickets_company_customer', ['company_id', 'customer_id', 'created_at'], unique=False)
        batch_op.create_index('ix_tickets_company_department', ['company_id', 'department_id'], unique=False)
        batch_op.create_index('ix_tickets_company_priority', ['company_id', 'priority_id'], unique=False)
        batch_op.create_index('ix_tickets_company_sla', ['company_id', 'sla_status'], unique=False)
        batch_op.create_index('ix_tickets_company_status', ['company_id', 'status_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_tickets_sla_scan', ['sla_status', 'resolution_due_at'], unique=False)

    op.create_table('customer_ratings',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_customer_ratings_rating_range')),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_customer_ratings_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_ratings_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_customer_ratings_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_customer_ratings_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_customer_ratings_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_ratings')),
    sa.UniqueConstraint('ticket_id', name=op.f('uq_customer_ratings_ticket_id'))
    )
    with op.batch_alter_table('customer_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_ratings_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_customer_ratings_company_created', ['company_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_ratings_department_id'), ['department_id'], unique=False)

    op.create_table('ticket_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_activities_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_activities_ticket_id_tickets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_activities_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_activities'))
    )
    with op.batch_alter_table('ticket_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_activities_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_ticket_activities_ticket_created', ['ticket_id', 'created_at'], unique=False)

    op.create_table('ticket_messages',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_messages_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_ticket_messages_deleted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_messages_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_messages_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_ticket_messages_ticket_created', ['ticket_id', 'created_at'], unique=False)

    op.create_table('ticket_reads',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_reads_ticket_id_tickets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_reads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id', name=op.f('pk_ticket_reads'))
    )
    with op.batch_alter_table('ticket_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_reads_user_id'), ['user_id'], unique=False)

    op.create_table('ticket_tag_relations',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['ticket_tags.id'], name=op.f('fk_ticket_tag_relations_tag_id_ticket_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_tag_relations_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id', name=op.f('pk_ticket_tag_relations'))
    )
    with op.batch_alter_table('ticket_tag_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_tag_relations_tag_id'), ['tag_id'], unique=False)

    op.create_table('ticket_attachments',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_attachments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], name=op.f('fk_ticket_attachments_message_id_ticket_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_attachments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_ticket_attachments_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_attachments'))
    )
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_attachments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_attachments_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_attachments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_message_mentions',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], name=op.f('fk_ticket_message_mentions_message_id_ticket_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_message_mentions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name=op.f('pk_ticket_message_mentions'))
    )
    with op.batch_alter_table('ticket_message_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_message_mentions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_message_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_message_mentions_user_id'))

    op.drop_table('ticket_message_mentions')
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_message_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_company_id'))

    op.drop_table('ticket_attachments')
    with op.batch_alter_table('ticket_tag_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_tag_relations_tag_id'))

    op.drop_table('ticket_tag_relations')
    with op.batch_alter_table('ticket_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_reads_user_id'))

    op.drop_table('ticket_reads')
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_messages_ticket_created')
        batch_op.drop_index(batch_op.f('ix_ticket_messages_company_id'))

    op.drop_table('ticket_messages')
    with op.batch_alter_table('ticket_activities', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_activities_ticket_created')
        batch_op.drop_index(batch_op.f('ix_ticket_activities_company_id'))

    op.drop_table('ticket_activities')
    with op.batch_alter_table('customer_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_ratings_department_id'))
        batch_op.drop_index('ix_customer_ratings_company_created')
        batch_op.drop_index(batch_op.f('ix_customer_ratings_agent_id'))

    op.drop_table('customer_ratings')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_tickets_sla_scan')
        batch_op.drop_index(batch_op.f('ix_tickets_deleted_at'))
        batch_op.drop_index('ix_tickets_company_status')
        batch_op.drop_index('ix_tickets_company_sla')
        batch_op.drop_index('ix_tickets_company_priority')
        batch_op.drop_index('ix_tickets_company_department')
        batch_op.drop_index('ix_tickets_company_customer')
        batch_op.drop_index('ix_tickets_company_created')
        batch_op.drop_index('ix_tickets_company_category')
        batch_op.drop_index('ix_tickets_company_agent')
        batch_op.drop_index(batch_op.f('ix_tickets_code'))

    op.drop_table('tickets')
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_categories_deleted_at'))
        batch_op.drop_index('ix_ticket_categories_company_parent')

    op.drop_table('ticket_categories')
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_sla_rules_lookup')

    op.drop_table('sla_rules')
    op.drop_table('knowledge_base_feedback')
    with op.batch_alter_table('department_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_users_user_id'))

    op.drop_table('department_users')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_codes_target')

    op.drop_table('verification_codes')
    op.drop_table('user_roles')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_sessions_family_id'))

    op.drop_table('sessions')
    op.drop_table('role_permissions')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_company_id'))

    op.drop_table('notifications')
    op.drop_table('notification_settings')
    with op.batch_alter_table('knowledge_base_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_base_articles_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_articles_category_id'))
        batch_op.drop_index('ix_kb_articles_company_status')

    op.drop_table('knowledge_base_articles')
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_index('ix_faqs_company_order')

    op.drop_table('faqs')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_departments_company_id'))

    op.drop_table('departments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_created')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_company_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_type'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('ticket_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_tags_company_id'))

    op.drop_table('ticket_tags')
    with op.batch_alter_table('ticket_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_statuses_company_id'))

    op.drop_table('ticket_statuses')
    with op.batch_alter_table('ticket_priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_priorities_company_id'))

    op.drop_table('ticket_priorities')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_company_id'))

    op.drop_table('roles')
    with op.batch_alter_table('knowledge_base_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_base_categories_company_id'))

    op.drop_table('knowledge_base_categories')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_company_id'))

    op.drop_table('holidays')
    with op.batch_alter_table('faq_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_categories_company_id'))

    op.drop_table('faq_categories')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_is_active'))
        batch_op.drop_index(batch_op.f('ix_companies_deleted_at'))

    op.drop_table('companies')
    op.drop_table('system_settings')
    op.drop_table('plans')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_group'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
